[profile.default]
src = "src"
out = "out"
libs = ["lib"]
cbor_metadata = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[etherscan]
unknown_chain = {
  key   = "${TENDERLY_ACCESS_TOKEN}",
  chain = 30,
  url   = "${TENDERLY_VIRTUAL_TESTNET_RPC_URL}/verify/etherscan"
}
